//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 09:52:31 AM CEST 
//


package dk.sds.samlh.xsd.userauthorizations;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.sts.xsd.userauthorizations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserAuthorizationList_QNAME = new QName("urn:dk:healthcare:saml:user_authorization_profile:1.0", "UserAuthorizationList");
    private final static QName _EducationCode_QNAME = new QName("urn:dk:healthcare:saml:user_authorization_profile:1.0", "EducationCode");
    private final static QName _AuthorizationCode_QNAME = new QName("urn:dk:healthcare:saml:user_authorization_profile:1.0", "AuthorizationCode");
    private final static QName _UserAuthorization_QNAME = new QName("urn:dk:healthcare:saml:user_authorization_profile:1.0", "UserAuthorization");
    private final static QName _EducationType_QNAME = new QName("urn:dk:healthcare:saml:user_authorization_profile:1.0", "EducationType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.sts.xsd.userauthorizations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserAuthorizationType }
     * 
     */
    public UserAuthorizationType createUserAuthorizationType() {
        return new UserAuthorizationType();
    }

    /**
     * Create an instance of {@link UserAuthorizationListType }
     * 
     */
    public UserAuthorizationListType createUserAuthorizationListType() {
        return new UserAuthorizationListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAuthorizationListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:dk:healthcare:saml:user_authorization_profile:1.0", name = "UserAuthorizationList")
    public JAXBElement<UserAuthorizationListType> createUserAuthorizationList(UserAuthorizationListType value) {
        return new JAXBElement<UserAuthorizationListType>(_UserAuthorizationList_QNAME, UserAuthorizationListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:dk:healthcare:saml:user_authorization_profile:1.0", name = "EducationCode")
    public JAXBElement<String> createEducationCode(String value) {
        return new JAXBElement<String>(_EducationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:dk:healthcare:saml:user_authorization_profile:1.0", name = "AuthorizationCode")
    public JAXBElement<String> createAuthorizationCode(String value) {
        return new JAXBElement<String>(_AuthorizationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAuthorizationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:dk:healthcare:saml:user_authorization_profile:1.0", name = "UserAuthorization")
    public JAXBElement<UserAuthorizationType> createUserAuthorization(UserAuthorizationType value) {
        return new JAXBElement<UserAuthorizationType>(_UserAuthorization_QNAME, UserAuthorizationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:dk:healthcare:saml:user_authorization_profile:1.0", name = "EducationType")
    public JAXBElement<String> createEducationType(String value) {
        return new JAXBElement<String>(_EducationType_QNAME, String.class, null, value);
    }

}
